#!/usr/bin/env bash
#
# Gives this Pi its own Web Push signing keys, so Sage can send a notification
# to a phone that is not on the same network.
#
# Run it once, on the Pi:
#
#     bash deploy/generate_vapid_keys.sh
#
# The keys are written to /etc/sage/sage.env, outside the repository and
# readable only by root. That matters: this repository is public, and the
# auto-sync daemon throws away anything it finds inside the checkout. A systemd
# drop-in points the backend at that file, so the keys survive both a sync and
# a re-run of install_native.sh.
#
# Running it a second time replaces the keys, which silently unsubscribes every
# device that is already receiving notifications. It asks first for that reason.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_DIR="/etc/sage"
ENV_FILE="$ENV_DIR/sage.env"
DROPIN_DIR="/etc/systemd/system/sage-backend.service.d"
PYTHON="$REPO_DIR/.venv/bin/python"

if [ ! -x "$PYTHON" ]; then
  PYTHON="$(command -v python3)"
fi

echo "Sage — Web Push keys"
echo

if sudo test -f "$ENV_FILE" && sudo grep -q '^VAPID_PUBLIC_KEY=' "$ENV_FILE"; then
  echo "This Pi already has keys in $ENV_FILE."
  echo "Replacing them will stop notifications on every device that is already"
  echo "signed up, and each one will have to turn them on again."
  echo
  read -r -p "Replace them? [y/N] " reply
  case "$reply" in
    [yY]*) ;;
    *) echo "Left alone."; exit 0 ;;
  esac
  echo
fi

# The keys are generated and checked in one step: a key that pywebpush cannot
# read back is worse than no key, because nothing fails until a reminder is due.
KEYS="$("$PYTHON" - <<'PY'
import base64
import sys

try:
    from cryptography.hazmat.primitives.asymmetric import ec
except ImportError:
    sys.exit("cryptography is missing. Run install_native.sh first, or:\n"
             "  .venv/bin/pip install -r backend/requirements.txt")

def b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode().rstrip("=")

private = ec.generate_private_key(ec.SECP256R1())
public = private.public_key()

# What the browser wants as applicationServerKey: the uncompressed point,
# 65 bytes beginning with 0x04.
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
public_raw = public.public_bytes(Encoding.X962, PublicFormat.UncompressedPoint)
private_raw = private.private_numbers().private_value.to_bytes(32, "big")

public_key = b64(public_raw)
private_key = b64(private_raw)

# Prove the backend can actually sign with this before it is written anywhere.
try:
    from py_vapid import Vapid01
    Vapid01.from_string(private_key=private_key).sign(
        {"aud": "https://example.com", "sub": "mailto:admin@raspberrypi.local"}
    )
except ImportError:
    print("note: pywebpush is not installed here, so the key was not test-signed",
          file=sys.stderr)
except Exception as exc:  # noqa: BLE001 — anything here means the key is unusable
    sys.exit(f"the generated key could not be used for signing: {exc}")

print(public_key)
print(private_key)
PY
)"

PUBLIC_KEY="$(echo "$KEYS" | sed -n 1p)"
PRIVATE_KEY="$(echo "$KEYS" | sed -n 2p)"

if [ -z "$PUBLIC_KEY" ] || [ -z "$PRIVATE_KEY" ]; then
  echo "Key generation produced nothing. Nothing was changed." >&2
  exit 1
fi

sudo mkdir -p "$ENV_DIR"
sudo tee "$ENV_FILE" > /dev/null <<EOF
# Web Push signing keys for this Pi. Generated by deploy/generate_vapid_keys.sh.
# Keep this file off the repository and out of any backup that leaves the house:
# the private key is what proves a notification came from Sage.
VAPID_PUBLIC_KEY=$PUBLIC_KEY
VAPID_PRIVATE_KEY=$PRIVATE_KEY
EOF
sudo chown root:root "$ENV_FILE"
sudo chmod 600 "$ENV_FILE"

# A drop-in rather than an edit to the unit, so re-running install_native.sh
# does not quietly take the keys away again.
sudo mkdir -p "$DROPIN_DIR"
sudo tee "$DROPIN_DIR/env.conf" > /dev/null <<EOF
[Service]
EnvironmentFile=-$ENV_FILE
EOF

sudo systemctl daemon-reload
sudo systemctl restart sage-backend

echo "Done."
echo
echo "  Keys:    $ENV_FILE  (root only)"
echo "  Public:  ${PUBLIC_KEY:0:12}…${PUBLIC_KEY: -6}"
echo
echo "Now open Sage, go to Settings, and turn Reminders on."
echo "On an iPhone, add Sage to the Home Screen first and open it from there —"
echo "Safari will not offer notifications to a plain tab."
